# Build command: USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose build
version: '3'
services:
  monolithic:
    build:
      context: .
      args: 
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    container_name: monolithic
    volumes:
      - ./:/opt/monolithic
    depends_on:
      - postgres
    ports:
      - 3000:3000
  postgres:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=''
volumes:
  postgres_data:
